import type { CategoryConfig } from "./types";

const ROAD_COLORS = [
  "roadsMotorway",
  "roadsTrunk",
  "roadsPrimary",
  "roadsSecondary",
  "roadsTertiary",
  "roadsMinor",
  "roadsService",
  "roadsPaths",
] as const;

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "labels",
    label: "Labels",
    controls: [
      { type: "switch", id: "labelsPlaceNames", label: "Place Names" },
      { type: "switch", id: "labelsRoadNames", label: "Road Names" },
      { type: "switch", id: "labelsRiverNames", label: "River Names" },
      { type: "switch", id: "labelsLakeNames", label: "Lake Names" },
      { type: "switch", id: "labelsPois", label: "POIs" },
    ],
  },
  {
    id: "water",
    label: "Water",
    controls: [
      {
        type: "color",
        id: "waterColor",
        label: "Color",
        sets: ["waterOcean", "waterLakes", "waterRivers", "waterStreams"],
      },
      { type: "switch", id: "waterOceanShow", label: "Show", group: "Ocean" },
      { type: "color", id: "waterOcean", label: "Color", group: "Ocean" },
      { type: "switch", id: "waterLakesShow", label: "Show", group: "Lakes" },
      { type: "color", id: "waterLakes", label: "Color", group: "Lakes" },
      { type: "switch", id: "waterRiversShow", label: "Show", group: "Rivers" },
      { type: "color", id: "waterRivers", label: "Color", group: "Rivers" },
      { type: "switch", id: "waterStreamsShow", label: "Show", group: "Streams" },
      { type: "color", id: "waterStreams", label: "Color", group: "Streams" },
      {
        type: "buttongroup",
        id: "waterwayDensity",
        label: "Waterway Density",
        min: 0,
        max: 5,
        step: 1,
        showKey: "waterStreamsShow",
        advanced: true,
      },
    ],
  },
  {
    id: "land",
    label: "Land",
    controls: [
      {
        type: "color",
        id: "landColor",
        label: "Color",
        sets: [
          "landBackground",
          "landForest",
          "landGrass",
          "landSand",
          "landSnow",
          "landParks",
          "landResidential",
        ],
      },
      { type: "color", id: "landBackground", label: "Background", advanced: true },
      { type: "color", id: "landForest", label: "Forest", advanced: true },
      { type: "color", id: "landGrass", label: "Grass", advanced: true },
      { type: "color", id: "landSand", label: "Sand", advanced: true },
      { type: "color", id: "landSnow", label: "Snow", advanced: true },
      { type: "color", id: "landParks", label: "Parks", advanced: true },
      { type: "color", id: "landResidential", label: "Residential", advanced: true },
    ],
  },
  {
    id: "roads",
    label: "Roads",
    controls: [
      { type: "switch", id: "roadsShow", label: "Show Roads" },
      {
        type: "color",
        id: "roadsColor",
        label: "Color",
        sets: [...ROAD_COLORS],
      },
      {
        type: "buttongroup",
        id: "roadsDensity",
        label: "Road Density",
        min: 1,
        max: 5,
        step: 1,
        showKey: "roadsShow",
      },
      {
        type: "slider",
        id: "roadsWidth",
        label: "Road Width",
        min: 0.5,
        max: 1.5,
        step: 0.05,
      },
      {
        type: "buttongroup",
        id: "roadsClarity",
        label: "Road Clarity",
        min: 0.5,
        max: 4,
        step: 0.5,
      },
      { type: "switch", id: "roadsMotorwayShow", label: "Show", group: "Motorway", advanced: true },
      { type: "color", id: "roadsMotorway", label: "Color", group: "Motorway", advanced: true },
      { type: "switch", id: "roadsTrunkShow", label: "Show", group: "Trunk", advanced: true },
      { type: "color", id: "roadsTrunk", label: "Color", group: "Trunk", advanced: true },
      { type: "switch", id: "roadsPrimaryShow", label: "Show", group: "Primary", advanced: true },
      { type: "color", id: "roadsPrimary", label: "Color", group: "Primary", advanced: true },
      { type: "switch", id: "roadsSecondaryShow", label: "Show", group: "Secondary", advanced: true },
      { type: "color", id: "roadsSecondary", label: "Color", group: "Secondary", advanced: true },
      { type: "switch", id: "roadsTertiaryShow", label: "Show", group: "Tertiary", advanced: true },
      { type: "color", id: "roadsTertiary", label: "Color", group: "Tertiary", advanced: true },
      { type: "switch", id: "roadsMinorShow", label: "Show", group: "Minor", advanced: true },
      { type: "color", id: "roadsMinor", label: "Color", group: "Minor", advanced: true },
      { type: "switch", id: "roadsServiceShow", label: "Show", group: "Service", advanced: true },
      { type: "color", id: "roadsService", label: "Color", group: "Service", advanced: true },
      { type: "switch", id: "roadsPathsShow", label: "Show", group: "Paths", advanced: true },
      { type: "color", id: "roadsPaths", label: "Color", group: "Paths", advanced: true },
    ],
  },
  {
    id: "buildings",
    label: "Buildings",
    controls: [
      { type: "switch", id: "buildingsShow", label: "Show Buildings" },
      { type: "color", id: "buildingsColor", label: "Color" },
      {
        type: "buttongroup",
        id: "buildingsDensity",
        label: "Building Density",
        min: 0,
        max: 5,
        step: 1,
        showKey: "buildingsShow",
        advanced: true,
      },
      { type: "color", id: "buildingsOutline", label: "Outline", advanced: true },
      {
        type: "slider",
        id: "buildingsOpacity",
        label: "Opacity",
        min: 0,
        max: 1,
        step: 0.05,
        advanced: true,
      },
    ],
  },
  {
    id: "borders",
    label: "Borders",
    controls: [
      { type: "switch", id: "bordersShow", label: "Show Borders" },
      { type: "color", id: "bordersColor", label: "Color" },
      {
        type: "slider",
        id: "bordersWidth",
        label: "Border Width",
        min: 0.5,
        max: 1.5,
        step: 0.05,
      },
    ],
  },
];
