import type { MapTemplate } from "@/lib/types";

export const minimal: MapTemplate = {
  name: "Minimal",
  config: {
    background: { color: "#ffffff" },
    land: {
      show: false,
      forest: { show: false, minzoom: 2 },
      grass: { show: false, minzoom: 2 },
      sand: { show: false, minzoom: 3 },
      ice: { show: false, minzoom: 3 },
      rock: { show: false, minzoom: 3 },
      wetland: { show: false, minzoom: 3 },
      farmland: { show: false, minzoom: 2 },
      residential: { show: false, minzoom: 1 },
      commercial: { show: false, minzoom: 3 },
      industrial: { show: false, minzoom: 3 },
      park: { show: false, minzoom: 1 },
    },
    water: {
      density: 5,
      ocean: { color: "#ffffff", opacity: 100, minzoom: 0 },
      lake: { color: "#ffffff", opacity: 100, minzoom: 2 },
      river: { show: false, minzoom: 6 },
      stream: { show: false, minzoom: 9 },
    },
    buildings: {
      show: true,
      color: "#e2e2e2",
      opacity: 100,
      minzoom: 4,
    },
    roads: {
      density: 5,
      lineCap: "round",
      lineJoin: "round",
      motorway: { color: "#1a1a1a", width: 1.2, minzoom: 0 },
      trunk: { color: "#1a1a1a", width: 1.1, minzoom: 1 },
      primary: { color: "#333333", width: 0.9, minzoom: 2 },
      secondary: { color: "#555555", width: 0.7, minzoom: 3 },
      tertiary: { color: "#777777", width: 0.5, minzoom: 4 },
      minor: { color: "#999999", width: 0.4, minzoom: 7 },
      service: { color: "#b3b3b3", width: 0.35, minzoom: 10 },
      path: { color: "#cccccc", width: 0.3, minzoom: 13 },
      track: { color: "#cccccc", width: 0.25, minzoom: 13 },
      pedestrian: { color: "#d9d9d9", width: 0.3, minzoom: 13 },
      street: { color: "#aaaaaa", width: 0.35, minzoom: 8 },
      street_limited: { color: "#aaaaaa", width: 0.35, minzoom: 8 },
      rail: { color: "#dddddd", width: 0.4, minzoom: 6 },
      transit: { color: "#dddddd", width: 0.35, minzoom: 8 },
    },
    borders: {
      country: { color: "#cccccc", width: 0.6, minzoom: 1 },
      state: { show: false, minzoom: 5 },
    },
    labels: {
      place: {
        color: "#111111",
        size: 15,
        transform: "uppercase",
        letterSpacing: 0.15,
        minzoom: 4,
      },
      road: { show: false, minzoom: 9 },
      river: { show: false, minzoom: 9 },
      lake: { show: false, minzoom: 9 },
      poi: { show: false, minzoom: 12 },
    },
  },
};
